# Generated by Django 4.2.5 on 2023-12-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lur_monitor', '0019_clients_pname'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(default=0, max_length=254)),
                ('message', models.TextField(max_length=500)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
    ]
