# Generated by Django 4.2.5 on 2023-12-27 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lur_monitor', '0020_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='leave_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'leave_type',
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('leave_type', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lur_monitor.leave_type')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lur_monitor.employee')),
            ],
            options={
                'db_table': 'Leave',
            },
        ),
    ]
