# Generated by Django 4.2.5 on 2023-12-28 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lur_monitor', '0023_alter_leave_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='date',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='start_date',
        ),
    ]
