# Generated by Django 4.2.5 on 2023-12-28 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lur_monitor', '0025_leave_date_leave_end_date_leave_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='date',
        ),
    ]
