# Generated by Django 4.2.5 on 2023-12-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lur_monitor', '0026_remove_leave_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='end_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
