# Generated by Django 4.2.5 on 2023-12-28 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lur_monitor', '0030_alter_leave_end_date_alter_leave_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='to',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
